"""
LODESTONE — state.py
====================
The shared state object that flows through every node in the LangGraph graph.
Every agent reads from this and writes back to it.

Think of this as the "memory" of one full conversation turn —
it accumulates as the graph executes and is reset between top-level queries
(but conversation_history persists across turns via the graph's checkpointer).
"""

from typing import TypedDict, Annotated, Optional
import operator


class EntityMemory(TypedDict):
    """
    Tracks confirmed real-world entities extracted from the conversation.
    Enables pronoun resolution — "they", "that company", "the CEO" — without
    re-asking the user or re-running the Clarity Agent from scratch.

    Example after turn 1:
        {
            "company_name": "Apple Inc.",
            "ticker":       "AAPL",
            "last_turn":    1
        }
    """
    company_name: Optional[str]   # confirmed full company name
    ticker:       Optional[str]   # stock ticker if found (helps financial search)
    last_turn:    Optional[int]   # which turn this entity was confirmed


class ResearchResult(TypedDict):
    """
    Output of one sub-intent research pass (news / financials / leadership / competitors).
    The Research Agent produces a list of these, one per intent.
    """
    intent:    str            # which sub-intent: "news", "financials", etc.
    summary:   str            # synthesized text from search results
    sources:   list[str]      # URLs or source labels
    raw_hits:  list[dict]     # full Tavily result objects (kept for Validator)


class AgentState(TypedDict):
    """
    The central state object passed between every node in the graph.

    LangGraph merges state at each node — fields annotated with
    `Annotated[list, operator.add]` APPEND across nodes instead of
    overwriting, which is correct behaviour for conversation_history.
    All other fields are simple overwrites (last writer wins).
    """

    # ── CONVERSATION ──────────────────────────────────────────────────────────
    conversation_history: Annotated[list[dict], operator.add]
    # Each entry: {"role": "user"|"assistant", "content": str, "turn": int}
    # Grows across turns. Agents receive the last N entries (capped by config).

    current_turn: int
    # Increments every time the user sends a new top-level message.

    # ── RAW + NORMALIZED INPUT ────────────────────────────────────────────────
    raw_input: str
    # Exactly what the user typed — never modified after capture.

    normalized_input: str
    # After tools/normalizer.py runs: typos fixed, whitespace cleaned,
    # ambiguity preserved (we don't "fix" vague references, just noise).

    # ── CLARITY AGENT OUTPUTS ─────────────────────────────────────────────────
    clarity_status: str
    # "clear" → proceed to Research
    # "needs_clarification" → trigger interrupt, ask user

    clarification_question: Optional[str]
    # The question to surface to the user when clarity_status = "needs_clarification"
    # e.g. "Which company are you referring to — Apple Inc. or Apple Records?"

    sub_intents: list[str]
    # Decomposed query intents — e.g. ["financials", "leadership"]
    # Research Agent runs one search pass per entry.
    # Defaults to all RESEARCH_INTENTS if query is broad.

    entity_memory: EntityMemory
    # Persists confirmed entity info across the conversation.
    # Updated by Clarity Agent on each turn.

    # ── RESEARCH AGENT OUTPUTS ────────────────────────────────────────────────
    research_results: list[ResearchResult]
    # One entry per sub_intent that was searched.

    confidence_score: float
    # 0–10. Assigned by the Research Agent based on:
    #   - number of sources found
    #   - source agreement
    #   - recency of results
    # Threshold from config.py routes to Validator (< 6) or Synthesis (≥ 6).

    source_conflict: bool
    # True if two or more sources disagree on a key fact.
    # Passed to Synthesis Agent to trigger a caveat block in the output.

    # ── VALIDATOR AGENT OUTPUTS ───────────────────────────────────────────────
    validation_result: str
    # "sufficient"   → route to Synthesis
    # "insufficient" → loop back to Research (if attempts < MAX_RESEARCH_RETRIES)

    research_attempts: int
    # Counts Research Agent invocations for this query.
    # Hard-capped at MAX_RESEARCH_RETRIES from config.py to prevent infinite loops.

    validator_notes: Optional[str]
    # Optional free-text from Validator explaining what's missing.
    # Research Agent reads this on retry to target the gap.

    # ── SYNTHESIS AGENT OUTPUT ────────────────────────────────────────────────
    final_response: str
    # The fully structured answer returned to the user.

    suggested_followups: list[str]
    # 2–3 follow-up questions generated by Synthesis.
    # Displayed as clickable buttons in the UI.
